import Head from "next/head";
import { useState } from "react";
import LoadCart from "./components/cart";
import LoadContact from "./components/contact";
import LoadHome from "./components/home";
import LoadMenu from "./components/menu";

export default function Home() {
  const [tab, setTab] = useState("home");
  const [cityIsKnown, setCityPrompt] = useState(1); // To add: Local Storage

  const CityPrompt = () => {
    if (cityIsKnown) {
      return (
        <>
          <div id="cityPrompt">
            Let us tell you if we have a restaurant in your region: "form"
          </div>
        </>
      );
    }
  };

  const LoadTab = () => {
    switch (tab) {
      case "home":
        return <LoadHome />;
      case "menu":
        return <LoadMenu />;
      case "contact":
        return <LoadContact />;
      case "cart":
        return <LoadCart />;
    }
  };

  return (
    <>
      <Head>
        <title>La Giorgio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flexSpacer">
        <CityPrompt />
        <div id="navBarContainer">
          <div id="navBar">
            <button className="BTN" id="homeBTN" onClick={() => setTab("home")}>
              La Giorgio
            </button>
            <div className="navContainer">
              <button
                className="BTN"
                id="menuBTN"
                onClick={() => setTab("menu")}
              >
                Menu
              </button>
              <button
                className="BTN"
                id="contactBTN"
                onClick={() => setTab("contact")}
              >
                Contact
              </button>
              <button
                className="BTN"
                id="cartBTN"
                onClick={() => setTab("cart")}
              >
                Cart
              </button>
            </div>
          </div>
        </div>
        <LoadTab />
      </div>
      <div id="footer">Average footer text and copyright thingy...</div>
    </>
  );
}
